package com.book;
// Generated Feb 18, 2020 9:36:30 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;




/**
 * Book generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Book  implements java.io.Serializable {


     private int id;
     private String name;
     private String author;
     private String publication;
     private List<Book> allStudent = new ArrayList<Book>();

    public Book() {
    }

	
    public Book(int id) {
        this.id = id;
    }
    public Book(int id, String name, String author, String publication) {
       this.id = id;
       this.name = name;
       this.author = author;
       this.publication = publication;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getPublication() {
        return this.publication;
    }
    
    public void setPublication(String publication) {
        this.publication = publication;
    }

    public void doInsert() {
        BookDAO ob = new BookDAO();
        ob.doAdd(this);
    }

    public String doUpdate() {
        BookDAO ob = new BookDAO();
        ob.doUpdate(this);
        return "show.xhtml";
    }

    public void doDelete() {
        BookDAO ob = new BookDAO();
        ob.doDelete(this);

    }

    public List<Book> getAllStudent() {
        BookDAO ob = new BookDAO();
        this.allStudent = ob.findAllStudent();
        return allStudent;
    }

    public void setAllStudent(List<Book> allStudent) {
        this.allStudent = allStudent;
    }


}


